### ISSUE TITLE
mongo journal/snapshot enjoys higher priority than configuration

### ISSUE THREAD

**Issue by sangszhou** [scullxbones/akka-persistence-mongo#59] opened 2015-10-28 00:06 UTC
I found that if two cluster share one mongodb(same database name) even with `different cluster name` will eventually merge to one cluster. 

It's really painful, because our cluster on dev are always trying to connect nodes on testbed. I know it must be someone in my team forget to modify mongo database name when starting cluster on testbed, but I don't know who it is since mongo journal/snapshot is not readable.

I am still using the 0.4.0 version of akka-persistence-mongo-rxmongo.

**Comment by matheuslima** [comment] 2015-10-28 01:01
the two cluster use same collection name to journal and snapshot?

**Comment by sangszhou** [comment] 2015-10-28 01:24
same db(collection) name, but different clustername @matheuslima

**Comment by matheuslima** [comment] 2015-10-28 01:34
Override the collection names of separated collections for each cluster

**Comment by scullxbones** [comment] 2015-10-28 02:09
Ah ok, now I understand what happened.  @matheuslima has a good answer above.

Was the expectation that the name of the cluster that the plugin was a member of would somehow adjust the mongo configuration?  Modify the db or collection names?  I'm trying to figure out what is meant by configuration priority.  Are seed nodes also shared between the two clusters?  That would explain them connecting to each other, I suppose.

This plugin is cluster-unaware, partly to make the minimum requirements of use less stringent, but also partly because I didn't really consider akka persistence and akka cluster to be dependent on each other.  The expectation so far has been that users would need to manage their `application.conf` settings for each deployment.

**Comment by sangszhou** [comment] 2015-10-28 02:25
@matheuslima  
I do know that solution. But the problem is that our developer(mostly our intern) might forget to override the collection name, but unlikely forgetting modify cluster name.

So, I wish nodes would only join to the cluster with same cluster name as akka cluster should does. But with akka-persistent-mongo, this principle no long holds.

**Comment by matheuslima** [comment] 2015-10-28 02:36
If you only want isolate dev environment, why not run mongo locally using docker or similar?

**Comment by matheuslima** [comment] 2015-10-28 02:39
Btw, are you using cluster sharding? Stateless cluster not needs persistence module. So if you are two clusters using same persistence, probably you will have data corruption, for example, the two clusters insert data do same persistence id.

**Comment by sangszhou** [comment] 2015-10-28 02:42
@matheuslima Yes, I am using cluster sharding.

**Comment by sangszhou** [comment] 2015-10-28 02:43
@matheuslima  I hope that akka-persistent-mongo would support that two cluster using same persistence collection if it not supported yet.

**Comment by matheuslima** [comment] 2015-10-28 02:48
akka persistence is not cluster aware, so this is not a bug, you cannot have two different clusters using same collections because it can lead to data corruption or application bugs.
Why you cannot have a local mongodb to dev tests? I use a docker image for mongo and works very well to my development environment.

**Comment by sangszhou** [comment] 2015-10-28 02:58
We got 4 configuration which are dev, stage, prod and local where local conf maintained by each developer and not allowed to push to trunk.

When a new developer or intern comes or new project is cloned, they tend to copy dev conf and modify some of it to make their own local conf. During this modification some things are forget to modify and their node connected to dev cluster

**Comment by matheuslima** [comment] 2015-10-28 03:04
well, I understand but unfortunately is not an akka issue.
Maybe better you commit to your git repository a version using environment  variables to select the mongo path.

**Comment by sangszhou** [comment] 2015-10-28 03:24
@matheuslima 

Nodes with different cluster name merged into one cluster,  because the use of akka-persistent-mongo, can this be considered as an issure?

**Comment by matheuslima** [comment] 2015-10-28 03:27
it sounds very weird. How two cluster with different name merge into one cluster? Makes no sense, seems an akka issue

**Comment by scullxbones** [comment] 2015-10-31 00:36
I'm going to close this ticket as out-of-scope.  At this point I don't want to couple so tightly to akka-cluster

**Closed by scullxbones** 2015-10-31 00:36 UTC
