### ISSUE TITLE
PersistentFSM serialization not working correctly

### ISSUE THREAD

**Issue by mladendinev** [scullxbones/akka-persistence-mongo#141] opened 2017-02-10 11:17 UTC
I have a persistent state model machine which persists the events to a mongo db successfully, but when I replay the events in the next run of the program it shows me this error? Any idea why I'm getting this?

```

2017-02-10 12:04:49 DEBUG Cursor:38 - There was an exception during the stream, dropping it since stopOnError is false
java.io.NotSerializableException: Can't deserialize object of type class java.lang.Object
	at akka.persistence.serialization.MessageSerializer.fromBinary(MessageSerializer.scala:75)
	at akka.persistence.serialization.MessageSerializer.fromBinary(MessageSerializer.scala:29)
	at akka.serialization.Serialization$$anonfun$deserialize$1.apply(Serialization.scala:122)
	at scala.util.Try$.apply(Try.scala:192)
	at akka.serialization.Serialization.deserialize(Serialization.scala:116)
	at akka.contrib.persistence.mongodb.Serialized.content$lzycompute(MongoDataModel.scala:38)
	at akka.contrib.persistence.mongodb.Serialized.content(MongoDataModel.scala:30)
	at akka.contrib.persistence.mongodb.Event.toRepr(MongoDataModel.scala:162)
	at akka.contrib.persistence.mongodb.RxMongoJournaller$$anonfun$replayJournal$1.apply(RxMongoJournaller.scala:175)
	at akka.contrib.persistence.mongodb.RxMongoJournaller$$anonfun$replayJournal$1.apply(RxMongoJournaller.scala:175)
	at play.api.libs.iteratee.Input$class.map(Iteratee.scala:236)
	at play.api.libs.iteratee.Input$El.map(Iteratee.scala:247)
	at play.api.libs.iteratee.Enumeratee$$anon$45$$anonfun$apply$23.apply(Enumeratee.scala:377)
	at play.api.libs.iteratee.Enumeratee$$anon$45$$anonfun$apply$23.apply(Enumeratee.scala:377)
	at play.api.libs.iteratee.Enumeratee$$anon$38$$anon$1$$anonfun$play$api$libs$iteratee$Enumeratee$$anon$$anon$$step$1$$anonfun$apply$11.apply(Enumeratee.scala:207)
	at play.api.libs.iteratee.Enumeratee$$anon$38$$anon$1$$anonfun$play$api$libs$iteratee$Enumeratee$$anon$$anon$$step$1$$anonfun$apply$11.apply(Enumeratee.scala:207)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)


```

**Comment by scullxbones** [comment] 2017-02-10 13:21
Hi @mladendinev -

It's tough to say with just the stack trace.

I think when i've seen this in the past the metadata that is supplied is incorrect, so while the data is written it cannot be read again.  It may be something as simple as having your events extend `Serializable`.  Or you may need to configure a serializer for your base trait, even if it's the Java `Serializable` serialization method.

There's more information in [the serialization section](http://doc.akka.io/docs/akka/2.4/scala/serialization.html) in the akka docs.  For example, you may get fail-fast behavior from the setting:

```
akka {
  actor {
    serialize-messages = on
  }
}
```

**Comment by mladendinev** [comment] 2017-02-13 10:30
Thank you for the quick reply, @scullxbones !

I did extend my event trait with `Serializable`, but that didn't solve the problem. What surprises me is that when I use the default leveldb plugin it serializes and replays the messages without any issues (again using the` Java Serializer`). Is it also normal my akka_persistent_metadata collection to be empty?

**Comment by scullxbones** [comment] 2017-02-20 05:28
Hi @mladendinev - I'm not sure what the difference is between the leveldb plugin and this one in regards to serialization, it's hard to say what the exact problem is without some kind of repeatable test case.

> Is it also normal my akka_persistent_metadata collection to be empty?

Yes, that tracks the maximum sequence number by persistence id.  What I meant by metadata is enough information for the plugin to decide what the payload type is.  From your report, it looks like the plugin only knows the type as `AnyRef` aka `java.lang.Object`.  Can you look at the journal collection in the mongo client?  It may help to see what was serialized.

**Comment by krzysztofbrzezinski** [comment] 2017-03-02 15:47
I work with @mladendinev on the same problem. The exact problem is that it fails to deserialize akka.persistence.fsm.PersistentFSM events because akka.persistence.serialization.MessageSerializer.fromBinary(bytes: Array[Byte], manifest: Option[Class[_]]) method gets wrong manifest which instead being that one which was persisted is java.lang.Object.
Data persisted in database are correct check below
![image](https://cloud.githubusercontent.com/assets/9767657/23513164/674cd6ac-ff63-11e6-95e4-a9a8ef331023.png)
By debugging library I found that the problem is with constructing Payload in selected lines of code: https://github.com/scullxbones/akka-persistence-mongo/blob/79665cf909afe93bd4e8bee8052dbccf9ca91418/common/src/main/scala/akka/contrib/persistence/mongodb/MongoDataModel.scala#L138-L142
When being during payload construction that is the passed properties and they were populated correctly
![image](https://cloud.githubusercontent.com/assets/9767657/23513393/233f0696-ff64-11e6-98be-1940a66b93c2.png)
Having set both clazzName and serId it disregards clazzName when serId is set as seen below because the first case would be fulfilled. 
```
case ("ser",ser:Array[Byte]) if serId.isDefined =>
   Serialized(ser, classOf[AnyRef], serId, serManifest)
case ("ser",ser:Array[Byte]) if clazzName.isDefined =>
   val clazz = loadClass(clazzName.get)
   Serialized(ser, clazz, serId, serManifest)
```
My suggestion is to switch the order of cases or if this order does make sense in any scenario I could not be aware simply add additional as written below
```
case ("ser",ser:Array[Byte]) if (clazzName.isDefined && serId.isDefined)=>
   val clazz = loadClass(clazzName.get)
   Serialized(ser, clazz, serId, serManifest)
case ("ser",ser:Array[Byte]) if serId.isDefined =>
   Serialized(ser, classOf[AnyRef], serId, serManifest)
case ("ser",ser:Array[Byte]) if clazzName.isDefined =>
   val clazz = loadClass(clazzName.get)
   Serialized(ser, clazz, serId, serManifest)
```

**Comment by scullxbones** [comment] 2017-03-02 16:00
Wow, that's a great write up.  Thank you @krzysztofbrzezinski !

The serialization id code was added with #137 not long ago.  Will dig deeper into that tonight to see what the best path might be.

**Comment by filosganga** [comment] 2017-03-02 17:25
Taking a look at the `akka.persistence.serialization.MessageSerializer` it includes the manifest. So the serialized event must have the `_sm` not null. But it is instead null. So there is an issue serializing the event on MongoDb somewhere.

**Comment by scullxbones** [comment] 2017-03-02 17:48
I don't have a lot of time to dedicate right this moment, but it looks like there may be some confusion on plain `Serializer` vs. `SerializerWithStringManifest`.  This class: `akka.persistence.serialization.MessageSerializer` is a plain serializer, but @filosganga I think you're referring to a `SerializerWithStringManifest` which allows for journal evolution - a very important feature.

I believe there's already special handling for both types in the Journal serialization code, will spend some time on it tonight.  If it's small enough, I should be able to get it into `1.4.1`

**Comment by filosganga** [comment] 2017-03-02 18:25
@krzysztofbrzezinski are you using casbah or reactive mongo?

@scullxbones does not really matter which serializer is in use. The manifest should be stored as a string in the same field. It will allow the  evolution later on and it is the Cassandra plugin implementation.

**Comment by filosganga** [comment] 2017-03-02 18:34
I will take a look at this as well as the version I am using in production is populating correctly the manifest from any serializer. I am using the casbah one.

**Comment by filosganga** [comment] 2017-03-02 19:30
@scullxbones I have found the issue

In this snippet at https://github.com/scullxbones/akka-persistence-mongo/blob/master/common/src/main/scala/akka/contrib/persistence/mongodb/MongoDataModel.scala#L51

```
object Serialized {
  def apply(any: AnyRef)(implicit ser: Serialization) = {
    val clazz = any.getClass
    ser.findSerializerFor(any) match {
      case s:SerializerWithStringManifest =>
        new Serialized(s.toBinary(any), clazz, Option(s.manifest(any)))
      case s =>
        new Serialized(s.toBinary(any), clazz, None)
    }
  }
}
```

It is not setting the serializer manifest.

**Comment by scullxbones** [comment] 2017-03-02 20:14
@filosganga - I saw that block.  But looking at the scaladocs for akka-serialization makes me think that the problem is elsewhere.  The method `s.manifest()` is only on `SerializerWithStringManifest`.  Other serializers use a `Class[_]` as the manifest i.e.
 
```scala
def fromBinary(bytes: Array[Byte], manifest: Option[Class[_]]): AnyRef
```

In other words, there's two types of manifest, `Class` for the older `Serializer`s that aren't that concerned about evolution, and `String` for newer `Serializer`s that are more concerned about evolution.  At least that's where i've arrived after reading scaladocs in `Serializer.scala` plus the [akka docs](http://doc.akka.io/docs/akka/2.4/scala/serialization.html).  Given that, I think the data model is probably correct, now that the `SerializerId` is also in place.

So i'm thinking the model is right and that the partial function mentioned by @krzysztofbrzezinski is probably not quite right.  I will definitely check out the Cassandra plugin (and I should also revisit the LevelDB plugin), mongo plugin users should be able to easily scale up / switch to that as needed.

**Comment by filosganga** [comment] 2017-03-02 20:48
@scullxbones The current model is not quite right, because it is setting the className even if the serializer has the `includeManifest` property false.

Don't get the two manifest are different types, they are the same concept. What the Cassandra plugin does is:

```
val serManifest = serializer match {
        case ser2: SerializerWithStringManifest ⇒
          ser2.manifest(event)
        case _ ⇒
          if (serializer.includeManifest) event.getClass.getName
          else PersistentRepr.Undefined
      }
```

At https://github.com/akka/akka-persistence-cassandra/blob/master/src/main/scala/akka/persistence/cassandra/journal/CassandraJournal.scala#L384

As you can see the manifest, even being a class, is optional, while the MongoDb plugin sets it always even if the serializer has the `includeManifest` false.

The change proposed by @krzysztofbrzezinski will screw up the logic, as the className is always defined in the current model and then even if the serializer is a SerializerWithStringManifest, it will not be able to deserialize anything as the `val clazz = loadClass(clazzName.get)` will trhrow a `ClassNotFoundException` whrn the class has changed its name.

**Comment by filosganga** [comment] 2017-03-02 21:03
The correct solution would be putting the manifest (class or string does not matter) in the `_sm` field  only if the serializer include it. And pass it back to the serializer as a String or class depending by the serializer.

The main issue is that the journal has lost the information wheather the manifest must be included or not.

Ideally will be possible to run a migration that:
 - Resolve the serializer given the `_si` or `_h`
 - Populate the `_sm` if the Serializer include the manifest
 - Remove the `_h` field

It will simplify all the logic and resolve this issue, but it is indeed an expensive change.
---
An alternative possible solution, little bit hacky, is passing the class to the serializer as manifest only if has the `includeManifest` `true` and trying to load the class at the end only if the `_si` is empty.

**Comment by scullxbones** [comment] 2017-03-03 05:25
Here's what i'm looking at currently as a fix. 

I was able to duplicate the serialization failure locally with an `AtLeastOnceDeliverySnapshot`, and confirm that the below fixes that.  I'll want to build out some `PersistentFSM` tests to be sure.

I think it satisfies both cases, but let me know if anything jumps out at you:

```scala
  private def loadClass(byName: String): Option[Class[_ <: AnyRef]] = {
...
  }

  def apply[D](hint: String, any: Any, clazzName: Option[String],
               serId: Option[Int], serManifest: Option[String])
              (implicit evs: Serialization, ev: Manifest[D], dt: DocumentType[D]):Payload =
    (hint,any) match {
      case ("repr",repr:Array[Byte]) => Legacy(repr)
      case ("ser",ser:Array[Byte]) =>
        val clazz = clazzName.flatMap(loadClass).getOrElse(classOf[AnyRef])
        Serialized(ser, clazz, serId, serManifest)
...
      case (x,y) => throw new IllegalArgumentException(s"Unknown hint $x or type for payload content $y")
    }
```

and (to address the `includeManifest = false` case)

```scala
case class Serialized[C <: AnyRef](bytes: Array[Byte],
                                   clazz: Class[C],
                                   serializerId: Option[Int],
                                   serializedManifest: Option[String])(implicit ser: Serialization) extends Payload {
  type Content = C

  val hint = "ser"
  lazy val content: C = {

    val resolvedSerializer = serializerId.map(ser.serializerByIdentity).getOrElse(ser.serializerFor(clazz))

    val tried = resolvedSerializer match {
      case s:SerializerWithStringManifest =>
        ser.deserialize(bytes, s.identifier, serializedManifest.getOrElse(clazz.getName))

      case s if s.includeManifest =>
        ser.deserialize(bytes, s.identifier, Option(clazz))

      case _ =>
        ser.deserialize(bytes, clazz)
    }

    tried match {
      case Success(deser) => deser.asInstanceOf[C]
      case Failure(x) => throw x
    }
  }
}
```

Right now, FSM serialization is not working - so I can't leave things the way they are.  I also have several users with very large, very old journals that have been around since Akka 2.3 & the 0.x versions.  A data migration has to clear a very high bar given how painful it is.

I'm going to take a bit more time on this, I want to start using `ExtendedActorSystem.DynamicAccess` instead of searching for a classloader, and I want to add `PersistentFSM` tests.

**Comment by filosganga** [comment] 2017-03-03 08:39
@scullxbones The `val clazz = clazzName.flatMap(loadClass).getOrElse(classOf[AnyRef])` will blow up when a class is renamed.

**Comment by scullxbones** [comment] 2017-03-03 12:09
It doesn't blow up, but there's no way for you to see that when I elide the method body.  My mistake.  Here it is below:

```scala
  private def loadClass(byName: String): Option[Class[_ <: AnyRef]] = {
    (Option(Thread.currentThread().getContextClassLoader) orElse
      Option(getClass.getClassLoader)
        ).flatMap(cl => Try(cl.loadClass(byName).asInstanceOf[Class[X forSome {type X <: AnyRef}]]).toOption)
  }
```

So for the scenario of the class no longer exists, this will resolve to `AnyRef`.  Which will probably cause this strange error again if a user changes class name, but doesn't account for it by keeping the serialization id and moving to a `StringBasedSerializer`.  I guess I can log something in that case.

**Comment by filosganga** [comment] 2017-03-03 12:37
I guess it is a good tradeoff.

**Comment by mladendinev** [comment] 2017-03-06 13:24
@scullxbones, can you confirm if the fix is already in place and if we can pull the new release?

**Comment by scullxbones** [comment] 2017-03-06 14:00
Hi @mladendinev i'll update this ticket when the release is pushed.  It will be after PR #145 gets merged for sure.  I expect version # to be `1.4.1`

**Comment by scullxbones** [comment] 2017-03-07 04:29
Fixed in `1.4.1`

**Closed by scullxbones** 2017-03-07 04:29 UTC
Labels: bug

**Comment by scullxbones** [comment] 2017-03-12 02:53
@mladendinev let me know if you have any more issues.  Thanks for reporting!

**Comment by krzysztofbrzezinski** [comment] 2017-03-12 18:11
Hi @scullxbones we tested it and happily by now we don't see any more issues. Thanks for fast fix!
